version: '1.0'
stages:
  - "Stage 1"
  - "Stage 2"
  - "Stage 3"
steps:
  one:
    title: GoLang
    stage: "Stage 1"
    image: golang:alpine
    commands:
      - echo '******* hello world *******'
  two:
    title: Java
    stage: "Stage 1"
    image: openjdk:21
    commands:
      - echo '******* hello world *******'
  three:
    title: .Net Core SDK
    stage: "Stage 1"
    image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
    commands:
      - echo '******* hello world *******'
      
  four:
    type: parallel
    stage: "Stage 2"
    steps:
    
        red:
          title: Golang
          image: golang:alpine
          commands:
            - echo '******* hello world *******'
            
        green:
          title: Java
          image: openjdk:21
          commands:
            - echo '******* hello world *******'
            
        blue:
          title: .Net Core SDK
          image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
          commands:
            - echo '******* hello world *******'
            
  final_stage:
    title: Final Stage
    stage: "Stage 3"
    image: alpine
    commands:
      - echo '******* hello world *******'   
