version: '1.0'
stages:
  - stage1
steps:
  hello_world_step:
    title: free style step
    stage: stage1
    image: alpine
    commands:
      - echo '******* hello world *******'
      - apk update && apk add openssh
